replicaCount: 2
image:
  repository: 163895578832.dkr.ecr.us-east-1.amazonaws.com/mission-status-api
  tag: "93f544c"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  ENV: dev
  APP_VERSION: "93f544c"
ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts:
    - host: mission-status.example.com
      paths:
        - path: /
          pathType: Prefix
serviceAccount:
  create: true
  name: ""
