replicaCount: 2
image:
  repository: 163895578832.dkr.ecr.us-east-1.amazonaws.com/mission-status-api
  tag: "823b34c"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  ENV: dev
  APP_VERSION: "latest"
  APP_NAME: "Mission Status API"
  CLOUD_PROVIDER: "aws"
  CLOUD_REGION: "us-east-1"
  CLUSTER_NAME: "mission-status-dev-eks"
  DEPLOYED_AT: "pipeline-managed"
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:163895578832:certificate/7c9cf695-5f2c-4144-b7a4-1ffb22126e4c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/load-balancer-name: mission-status-dev-alb
  hosts:
    - host: app.kanedata.net
      paths:
        - path: /
          pathType: Prefix
serviceAccount:
  create: true
  name: ""
fullnameOverride: mission-status-api
