apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mission-status-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/essiea/mission-status-api.git
    targetRevision: main
    path: helm/mission-status-api
  destination:
    server: https://kubernetes.default.svc
    namespace: mission-status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
